apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
 name: prometheus-ssl
 namespace: monitoring
spec:
 acme:
   # The ACME server URL
   server: https://acme-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: kerupuk.lovers@gmail.com
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: prometheus-ssl
   # Enable the HTTP-01 challenge provider
   solvers:
   - selector: {}
     http01:
       ingress:
         class:  nginx
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
  
spec:
  selector: 
    app: prometheus-server
  #type: NodePort  
  ports:
    - port: 8080
      targetPort: 9090 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "prometheus-ssl"
spec:
  rules:
  - host: prometheus.rafifauz.site
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: prometheus-service
          servicePort: 8080
  
  tls:
  - hosts:
    - prometheus.rafifauz.site
    secretName: prometheus-tls

