---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
 name: grafana-ssl
 namespace: monitoring
spec:
 acme:
   # The ACME server URL
   server: https://acme-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: kerupuk.lovers@gmail.com
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: grafana-ssl
   # Enable the HTTP-01 challenge provider
   solvers:
   - selector: {}
     http01:
       ingress:
         class:  nginx
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  selector: 
    app: grafana
  #type: NodePort  
  ports:
    - port: 3000
      targetPort: 3000
      #nodePort: 32000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "grafana-ssl"
spec:
  rules:
  - host: grafana.rafifauz.site
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: grafana-service
          servicePort: 3000
  
  tls:
  - hosts:
    - grafana.rafifauz.site
    secretName: grafana-tls

