apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  ports:
    - port: 4000
      protocol: TCP
  selector:
    app: server
#  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: backend.rafifauz.site
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: server-service
          servicePort: 4000
