apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-port
  selector:
    app: client
#  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: frontend.rafifauz.site
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: client-service
          servicePort: 80
