apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    app: mongodb
#  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mongo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: mongo.rafifauz.site
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: mongodb-service
          servicePort: 27017
